name: CI - Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
      NODE_ENV: test
      JWT_SECRET: testsecret
      JWT_REFRESH_SECRET: testrefreshsecret
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Esperar a que Postgres esté listo
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done
      - name: Ejecutar migraciones (opcional)
        run: |
          # Si tienes migraciones, agrégalas aquí
          echo "No hay migraciones configuradas"
      - name: Ejecutar tests y coverage
        run: npm run test:coverage
